"""
AUTO-GENERATED by worldsim-workspace/repo-setup/sync-all.sh — DO NOT EDIT.

Канонический источник: worldsim-workspace/packages/schemas/src/worldsim_schemas/

Любая правка тут перетрётся при следующем sync. Изменения делаются в
workspace, затем `./repo-setup/sync-all.sh`. CI-скрипт sync-check.sh падает,
если файлы здесь расходятся с манифестом.
"""
